export const workspaces = [
  {
    id: "signaldesk",
    name: "SignalDesk",
    subtitle: "AI Operations Center",
    accent: "#7c3aed",
    accentDark: "#6d28d9",
    initials: "S",
    description: "Live operations overview",
    kpi: {
      openTickets: "Open Tickets",
      activeSignals: "Active Signals",
      criticalIncidents: "Critical Incidents",
      pendingDrafts: "Pending Drafts",
    },
    ticketCategories: [
      { value: "billing", label: "Billing" },
      { value: "technical", label: "Technical" },
      { value: "account", label: "Account" },
      { value: "general", label: "General" },
    ],
    signalCategories: ["billing", "technical", "security", "account", "refund"],
    knowledge: {
      title: "Knowledge Base",
      subtitle: "Organizational memory and learned patterns from resolved signals.",
    },
    aiContext: "Review and approve AI-generated draft responses for customer support tickets.",
  },
  {
    id: "corally",
    name: "Corally",
    subtitle: "SaaS Support Platform",
    accent: "#f43f5e",
    accentDark: "#e11d48",
    initials: "C",
    description: "Customer operations overview",
    kpi: {
      openTickets: "Open Cases",
      activeSignals: "User Reports",
      criticalIncidents: "Critical Bugs",
      pendingDrafts: "Pending Responses",
    },
    ticketCategories: [
      { value: "billing", label: "Subscription" },
      { value: "technical", label: "Platform Bug" },
      { value: "account", label: "Account Access" },
      { value: "feature", label: "Feature Request" },
    ],
    signalCategories: ["billing", "technical", "security", "account", "feature"],
    knowledge: {
      title: "SaaS Knowledge",
      subtitle: "Platform incident patterns and customer issue resolution history.",
    },
    aiContext: "Review and approve AI-generated draft responses for SaaS platform customer support cases.",
  },
  {
    id: "foxo",
    name: "Foxo",
    subtitle: "Streaming Operations",
    accent: "#10b981",
    accentDark: "#059669",
    initials: "F",
    description: "Service health overview",
    kpi: {
      openTickets: "Open Issues",
      activeSignals: "Stream Alerts",
      criticalIncidents: "Critical Outages",
      pendingDrafts: "Pending Replies",
    },
    ticketCategories: [
      { value: "streaming", label: "Stream Quality" },
      { value: "account", label: "Account Issue" },
      { value: "billing", label: "Payment" },
      { value: "content", label: "Content Request" },
    ],
    signalCategories: ["streaming", "billing", "security", "account", "content"],
    knowledge: {
      title: "Streaming Knowledge",
      subtitle: "Content delivery patterns, outage learnings, and user experience insights.",
    },
    aiContext: "Review and approve AI-generated draft responses for streaming service support tickets.",
  },
  {
    id: "binocs",
    name: "Binocs",
    subtitle: "Enterprise Analytics",
    accent: "#6366f1",
    accentDark: "#4f46e5",
    initials: "B",
    description: "Analytics operations overview",
    kpi: {
      openTickets: "Open Queries",
      activeSignals: "Data Anomalies",
      criticalIncidents: "Critical Findings",
      pendingDrafts: "Pending Reviews",
    },
    ticketCategories: [
      { value: "data", label: "Data Query" },
      { value: "technical", label: "Infrastructure" },
      { value: "account", label: "Account Admin" },
      { value: "reporting", label: "Report Issue" },
    ],
    signalCategories: ["data", "technical", "security", "account", "reporting"],
    knowledge: {
      title: "Analytics Knowledge",
      subtitle: "Data pipeline incident patterns and enterprise reporting resolutions.",
    },
    aiContext: "Review and approve AI-generated draft responses for enterprise analytics support tickets.",
  },
  {
    id: "zap",
    name: "Zap",
    subtitle: "Delivery Platform",
    accent: "#f59e0b",
    accentDark: "#d97706",
    initials: "Z",
    description: "Delivery operations overview",
    kpi: {
      openTickets: "Open Orders",
      activeSignals: "Delivery Alerts",
      criticalIncidents: "Critical Delays",
      pendingDrafts: "Pending Responses",
    },
    ticketCategories: [
      { value: "delivery", label: "Delivery Issue" },
      { value: "billing", label: "Payment" },
      { value: "account", label: "Account" },
      { value: "merchant", label: "Merchant Support" },
    ],
    signalCategories: ["delivery", "billing", "security", "account", "merchant"],
    knowledge: {
      title: "Delivery Knowledge",
      subtitle: "Logistics incident patterns, delay learnings, and merchant resolutions.",
    },
    aiContext: "Review and approve AI-generated draft responses for delivery platform support tickets.",
  },
  {
    id: "yesmadam",
    name: "YesMadam",
    subtitle: "Beauty & Wellness",
    accent: "#ec4899",
    accentDark: "#db2777",
    initials: "Y",
    description: "Customer care overview",
    kpi: {
      openTickets: "Open Inquiries",
      activeSignals: "Trend Alerts",
      criticalIncidents: "Critical Complaints",
      pendingDrafts: "Pending Responses",
    },
    ticketCategories: [
      { value: "product", label: "Product Inquiry" },
      { value: "order", label: "Order Issue" },
      { value: "billing", label: "Billing" },
      { value: "consultation", label: "Consultation" },
    ],
    signalCategories: ["product", "order", "billing", "account", "consultation"],
    knowledge: {
      title: "Beauty Knowledge",
      subtitle: "Product feedback patterns, consultation insights, and trend learnings.",
    },
    aiContext: "Review and approve AI-generated draft responses for beauty and wellness customer care tickets.",
  },
];

export const DEFAULT_WORKSPACE_ID = "signaldesk";

export function getWorkspace(id) {
  return workspaces.find((w) => w.id === id) || workspaces.find((w) => w.id === DEFAULT_WORKSPACE_ID);
}
