import { Bot, FileText, Sparkles } from "lucide-react";
import { useState } from "react";

export default function DraftCard({ ticket }) {

  const [draft, setDraft] = useState(ticket.draftReply);

  return (
    <div className="rounded-xl border border-violet-200 bg-violet-50 p-6">

      <div className="flex items-center justify-between">

        <div className="flex items-center gap-3">

          <div className="rounded-lg bg-violet-100 p-2">
            <Bot className="text-violet-600" size={20} />
          </div>

          <div>
            <h2 className="text-xl font-semibold text-zinc-900">
              AI Draft Reply
            </h2>

            <p className="text-sm text-zinc-500">
              Generated by reply-agent
            </p>

          </div>

        </div>

        <Sparkles className="text-violet-500" />

      </div>

      <textarea
        value={draft}
        onChange={(e) => setDraft(e.target.value)}
        className="mt-6 h-72 w-full rounded-xl border border-[#EFEFEF] bg-white p-5 text-zinc-900 outline-none resize-none"
      />

      <div className="mt-6">

        <h3 className="mb-4 flex items-center gap-2 text-sm font-medium text-zinc-700">

          <FileText size={16} />

          Knowledge Sources

        </h3>

        <div className="space-y-2">

          {ticket.knowledgeSources.map((item) => (

            <div
              key={item}
              className="rounded-lg bg-white border border-[#EFEFEF] p-3 text-sm text-zinc-700"
            >
              {item}
            </div>

          ))}

        </div>

      </div>

    </div>
  );

}
