import { Bot, FileText, Sparkles } from "lucide-react";
import { useState } from "react";

export default function DraftCard({ ticket }) {

  const [draft, setDraft] = useState(ticket.draftReply);

  return (
    <div className="rounded-xl border border-violet-700/40 bg-gradient-to-br from-zinc-900 to-zinc-950 p-6">

      <div className="flex items-center justify-between">

        <div className="flex items-center gap-3">

          <div className="rounded-lg bg-violet-600/20 p-2">
            <Bot className="text-violet-400" size={20} />
          </div>

          <div>
            <h2 className="text-xl font-semibold">
              AI Draft Reply
            </h2>

            <p className="text-sm text-zinc-500">
              Generated by reply-agent
            </p>

          </div>

        </div>

        <Sparkles className="text-violet-400" />

      </div>

      <textarea
        value={draft}
        onChange={(e) => setDraft(e.target.value)}
        className="mt-6 h-72 w-full rounded-xl border border-zinc-800 bg-zinc-950 p-5 outline-none resize-none"
      />

      <div className="mt-6">

        <h3 className="mb-4 flex items-center gap-2">

          <FileText size={16} />

          Knowledge Sources

        </h3>

        <div className="space-y-2">

          {ticket.knowledgeSources.map((item) => (

            <div
              key={item}
              className="rounded-lg bg-zinc-900 p-3"
            >
              {item}
            </div>

          ))}

        </div>

      </div>

    </div>
  );

}