import { motion } from "framer-motion";
import { useState, useMemo } from "react";
import { Plus, MoreHorizontal, Calendar, Paperclip, MessageSquare, List, Columns3, LayoutGrid, ExternalLink, Copy, Check, X, Code, FileText } from "lucide-react";
import { useLemmaRecords } from "@/hooks/useLemmaRecords";
import { useRefreshListener } from "@/lib/refreshEvents";
import { toast } from "sonner";
import client from "@/lib/lemmaClient";
import { useWorkspace } from "@/context/WorkspaceContext";
import useRole from "@/hooks/useRole";

const TAG_STYLES = {
  billing: "bg-green-100 text-green-700",
  refund: "bg-purple-100 text-purple-700",
  urgent: "bg-orange-100 text-orange-700",
  technical: "bg-blue-100 text-blue-700",
  account: "bg-pink-100 text-pink-700",
  security: "bg-red-100 text-red-700",
  streaming: "bg-cyan-100 text-cyan-700",
  content: "bg-amber-100 text-amber-700",
  feature: "bg-indigo-100 text-indigo-700",
  data: "bg-teal-100 text-teal-700",
  reporting: "bg-sky-100 text-sky-700",
  delivery: "bg-orange-100 text-orange-700",
  merchant: "bg-yellow-100 text-yellow-700",
  product: "bg-fuchsia-100 text-fuchsia-700",
  order: "bg-lime-100 text-lime-700",
  consultation: "bg-rose-100 text-rose-700",
};

const PRIORITY_STYLES = {
  urgent: "bg-red-100 text-red-700",
  high: "bg-orange-100 text-orange-700",
  normal: "bg-blue-100 text-blue-700",
  low: "bg-zinc-100 text-zinc-500",
};

const COLUMNS = [
  { id: "pending", label: "New", color: "bg-zinc-900" },
  { id: "approved", label: "In Review", color: "bg-blue-500" },
  { id: "memory", label: "Resolved", color: "bg-green-500" },
];

const AVATARS = ["JD", "AK", "SM", "RP", "TL"];
const COMMENTS = [1, 2, 0, 3, 1, 0, 2, 4, 1, 0, 2, 1, 0, 3, 2];
const ATTACHMENTS = [2, 0, 1, 3, 0, 1, 2, 0, 1, 2, 0, 1, 3, 0, 1];

function getTagStyle(category) {
  const key = (category || "").toLowerCase();
  return TAG_STYLES[key] || "bg-zinc-100 text-zinc-600";
}

function getPriorityStyle(priority) {
  return PRIORITY_STYLES[priority] || PRIORITY_STYLES.normal;
}

function openInLinear(signal) {
  const title = signal.name || signal.summary || signal.id;

  const description = `# ${title}

## Problem
${signal.summary || signal.ai_summary || ""}

## Impact
- Severity: ${signal.severity || signal.proposed_priority || "N/A"}
- Related Tickets: ${signal.related_ticket_count || signal.ticket_count || 0}
- First Seen: ${signal.detected_at ? new Date(signal.detected_at).toLocaleDateString() : "N/A"}

## Recommended Action
${signal.recommendation || ""}

Generated by SignalDesk.`;

  const p = (signal.proposed_priority || signal.severity || "").toLowerCase();
  const linearPriority = (p === "critical" || p === "high") ? 1 : p === "medium" ? 2 : 3;

  const params = new URLSearchParams({ title, description, priority: linearPriority });
  const url = `https://linear.app/signaldesk-demo/issue/new?${params.toString()}`;

  toast.success("Opening in Linear...");
  window.open(url, "_blank", "noopener,noreferrer");
}

function KanbanCard({ signal, index: cardIndex, isManager, onExport }) {
  const avatars = useMemo(() => {
    const count = (cardIndex % 3) + 2;
    return AVATARS.slice(0, count);
  }, [cardIndex]);

  const commentCount = useMemo(() => COMMENTS[cardIndex % COMMENTS.length], [cardIndex]);
  const attachmentCount = useMemo(() => ATTACHMENTS[cardIndex % ATTACHMENTS.length], [cardIndex]);

  const progress = useMemo(() => {
    if (signal.status === "memory") return 100;
    if (signal.status === "approved") return 60;
    return Math.min(25 + (signal.analysis_confidence || 0) * 0.3, 45);
  }, [signal]);

  return (
    <div className="group rounded-xl border border-[#EFEFEF] bg-white p-4 transition-all hover:border-zinc-200">
      <div className="mb-3 flex items-start justify-between gap-2">
        <div className="flex flex-wrap gap-1.5">
          {signal.category && (
            <span className={`rounded-md px-2 py-0.5 text-[10px] font-semibold ${getTagStyle(signal.category)}`}>
              {signal.category}
            </span>
          )}
          {(signal.proposed_priority || signal.severity) && (
            <span className={`rounded-md px-2 py-0.5 text-[10px] font-semibold ${getPriorityStyle(signal.proposed_priority || signal.severity)}`}>
              {(signal.proposed_priority || signal.severity).charAt(0).toUpperCase() + (signal.proposed_priority || signal.severity).slice(1)}
            </span>
          )}
        </div>
        <button className="flex-shrink-0 rounded p-1 text-zinc-300 opacity-0 transition-all hover:bg-zinc-100 hover:text-zinc-600 group-hover:opacity-100">
          <MoreHorizontal size={14} />
        </button>
      </div>

      <h3 className="mb-2.5 text-sm font-semibold leading-snug text-zinc-900 line-clamp-2">
        {signal.name || signal.summary || signal.id}
      </h3>

      {signal.detected_at && (
        <div className="mb-3 flex items-center gap-1.5 text-xs text-zinc-400">
          <Calendar size={12} />
          {new Date(signal.detected_at).toLocaleDateString("en-US", { day: "numeric", month: "short", year: "numeric" })}
        </div>
      )}

      <div className="mb-3">
        <div className="flex items-center justify-between mb-1">
          <span className="text-[10px] font-medium text-zinc-400">{progress}%</span>
        </div>
        <div className="h-1.5 rounded-full bg-zinc-100">
          <div
            className="h-1.5 rounded-full transition-all"
            style={{ width: `${progress}%`, backgroundColor: "var(--accent)" }}
          />
        </div>
      </div>

      {isManager && signal.status === "approved" && (
        <button
          onClick={(e) => { e.stopPropagation(); onExport?.(signal); }}
          className="mb-3 flex w-full items-center justify-center gap-2 rounded-lg border border-[#EFEFEF] bg-white py-2 text-xs font-medium text-zinc-600 transition hover:border-zinc-200 hover:bg-zinc-50"
        >
          <ExternalLink size={13} />
          Export to Roadmap
        </button>
      )}

      <div className="flex items-center justify-between">
        <div className="flex items-center">
          <div className="flex -space-x-1.5">
            {avatars.map((a, i) => (
              <div
                key={i}
                className="flex h-6 w-6 items-center justify-center rounded-full border border-white bg-zinc-200 text-[8px] font-semibold text-zinc-600"
              >
                {a}
              </div>
            ))}
          </div>
        </div>
        <div className="flex items-center gap-3">
          {attachmentCount > 0 && (
            <span className="flex items-center gap-1 text-[11px] text-zinc-400">
              <Paperclip size={12} />
              {attachmentCount}
            </span>
          )}
          {commentCount > 0 && (
            <span className="flex items-center gap-1 text-[11px] text-zinc-400">
              <MessageSquare size={12} />
              {commentCount}
            </span>
          )}
        </div>
      </div>
    </div>
  );
}

function RoadmapExportModal({ signal, onClose }) {
  const [copied, setCopied] = useState(null);

  const markdown = `# ${signal.name || signal.summary || signal.id}

## Summary
${signal.summary || signal.ai_summary || ""}

## Category
${signal.category || "N/A"}

## Priority
${signal.proposed_priority || signal.severity || "N/A"}

## Related Tickets
${signal.related_ticket_count || signal.ticket_count || 0}

## First Seen
${signal.detected_at ? new Date(signal.detected_at).toISOString().split("T")[0] : "N/A"}

## Recommendation
${signal.recommendation || ""}

---
Generated by SignalDesk`;

  const json = JSON.stringify({
    title: signal.name || signal.summary || signal.id,
    summary: signal.summary || signal.ai_summary || "",
    category: signal.category || null,
    priority: signal.proposed_priority || signal.severity || null,
    related_tickets: signal.related_ticket_count || signal.ticket_count || 0,
    first_seen: signal.detected_at || null,
    recommendation: signal.recommendation || null,
  }, null, 2);

  const handleCopy = async (text, label) => {
    try {
      await navigator.clipboard.writeText(text);
      setCopied(label);
      toast.success(`${label} copied`);
      setTimeout(() => setCopied(null), 2000);
    } catch {
      toast.error("Failed to copy");
    }
  };

  const handleOpenLinear = () => {
    openInLinear(signal);
    onClose();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 backdrop-blur-sm">
      <div className="w-full max-w-2xl max-h-[90vh] overflow-y-auto rounded-xl border border-[#EFEFEF] bg-white p-6">
        <div className="mb-5 flex items-center justify-between">
          <h2 className="text-lg font-bold">Export to Roadmap</h2>
          <button onClick={onClose} className="text-zinc-400 hover:text-zinc-700 transition-colors">
            <X size={20} />
          </button>
        </div>

        <div className="mb-4 rounded-lg border border-[#EFEFEF] bg-zinc-50 p-3">
          <div className="flex items-center justify-between mb-2">
            <div className="flex items-center gap-2">
              <FileText size={15} className="text-zinc-500" />
              <span className="text-xs font-semibold text-zinc-500 uppercase tracking-wide">Markdown</span>
            </div>
            <button
              onClick={() => handleCopy(markdown, "Markdown")}
              className="flex items-center gap-1.5 rounded-lg border border-[#EFEFEF] bg-white px-3 py-1.5 text-xs font-medium text-zinc-500 hover:text-zinc-700 transition-colors"
            >
              {copied === "Markdown" ? <Check size={13} className="text-green-500" /> : <Copy size={13} />}
              {copied === "Markdown" ? "Copied" : "Copy"}
            </button>
          </div>
          <pre className="overflow-x-auto rounded-lg bg-white p-3 text-xs leading-relaxed text-zinc-700 whitespace-pre-wrap font-mono max-h-48">{markdown}</pre>
        </div>

        <div className="mb-5 rounded-lg border border-[#EFEFEF] bg-zinc-50 p-3">
          <div className="flex items-center justify-between mb-2">
            <div className="flex items-center gap-2">
              <Code size={15} className="text-zinc-500" />
              <span className="text-xs font-semibold text-zinc-500 uppercase tracking-wide">JSON</span>
            </div>
            <button
              onClick={() => handleCopy(json, "JSON")}
              className="flex items-center gap-1.5 rounded-lg border border-[#EFEFEF] bg-white px-3 py-1.5 text-xs font-medium text-zinc-500 hover:text-zinc-700 transition-colors"
            >
              {copied === "JSON" ? <Check size={13} className="text-green-500" /> : <Copy size={13} />}
              {copied === "JSON" ? "Copied" : "Copy"}
            </button>
          </div>
          <pre className="overflow-x-auto rounded-lg bg-white p-3 text-xs leading-relaxed text-zinc-700 whitespace-pre-wrap font-mono max-h-48">{json}</pre>
        </div>

        <button
          onClick={handleOpenLinear}
          className="flex w-full items-center justify-center gap-2 rounded-lg bg-zinc-900 py-3 text-sm font-medium text-white hover:bg-zinc-800 transition-colors"
        >
          <ExternalLink size={15} />
          Open in Linear
        </button>
      </div>
    </div>
  );
}

function CreateSignalForm({ onClose, onCreated }) {
  const [form, setForm] = useState({ name: "", summary: "", category: "" });
  const [submitting, setSubmitting] = useState(false);
  const { workspace } = useWorkspace();

  const handleCreate = async () => {
    if (!form.name) return;
    setSubmitting(true);
    try {
      await client.functions.run("create_signal", {
        input: { title: form.name, summary: form.summary, category: form.category || "general" },
      });
      onCreated();
      onClose();
    } catch (err) {
      console.error(err);
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <div className="space-y-3 p-3">
      <input
        placeholder="Signal name"
        value={form.name}
        onChange={(e) => setForm({ ...form, name: e.target.value })}
        className="w-full rounded-lg border border-[#EFEFEF] bg-white p-2.5 text-sm outline-none focus:border-zinc-400"
      />
      <textarea
        placeholder="Summary"
        rows={3}
        value={form.summary}
        onChange={(e) => setForm({ ...form, summary: e.target.value })}
        className="w-full rounded-lg border border-[#EFEFEF] bg-white p-2.5 text-sm outline-none focus:border-zinc-400 resize-none"
      />
      <select
        value={form.category}
        onChange={(e) => setForm({ ...form, category: e.target.value })}
        className="w-full rounded-lg border border-[#EFEFEF] bg-white p-2.5 text-sm outline-none"
      >
        <option value="">Select category</option>
        {workspace.signalCategories.map((cat) => (
          <option key={cat} value={cat}>{cat.charAt(0).toUpperCase() + cat.slice(1)}</option>
        ))}
      </select>
      <div className="flex gap-2">
        <button
          onClick={handleCreate}
          disabled={submitting || !form.name}
          className="flex-1 rounded-lg bg-zinc-900 py-2.5 text-sm font-medium text-white hover:bg-zinc-800 disabled:opacity-50 transition"
        >
          {submitting ? "Creating..." : "Create"}
        </button>
        <button onClick={onClose} className="rounded-lg border border-[#EFEFEF] px-4 py-2.5 text-sm text-zinc-500 hover:text-zinc-900 transition">
          Cancel
        </button>
      </div>
    </div>
  );
}

export default function Signals() {
  const { workspace } = useWorkspace();
  const { isManager } = useRole();
  const { data: signals, loading, refresh } = useLemmaRecords("signals", { limit: 100 });
  useRefreshListener(refresh);
  const [creatingIn, setCreatingIn] = useState(null);
  const [exportSignal, setExportSignal] = useState(null);

  const columns = useMemo(() => {
    return COLUMNS.map((col) => ({
      ...col,
      cards: signals.filter((s) => {
        if (col.id === "pending") return s.status === "pending" || !s.status;
        if (col.id === "approved") return s.status === "approved";
        if (col.id === "memory") return s.status === "memory";
        return false;
      }),
    }));
  }, [signals]);

  return (
    <motion.div
      className="flex flex-col min-h-full"
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      transition={{ duration: 0.2 }}
    >
      <div className="sticky top-0 z-10 bg-white pb-4">
        <div className="flex items-center justify-between">
          <h1 className="text-2xl font-bold tracking-tight">Signals</h1>
          <div className="flex items-center gap-2">
            <div className="flex items-center rounded-lg border border-[#EFEFEF] overflow-hidden">
              <button className="flex items-center gap-1.5 px-3 py-2 text-xs font-medium bg-zinc-900 text-white">
                <Columns3 size={14} />
                Kanban
              </button>
              <button className="flex items-center gap-1.5 px-3 py-2 text-xs font-medium text-zinc-500 hover:bg-zinc-50">
                <List size={14} />
                List
              </button>
            </div>
          </div>
        </div>
      </div>

      {loading ? (
        <div className="flex gap-6 flex-1">
          {[1, 2, 3].map((i) => (
            <div key={i} className="flex-1 space-y-3">
              <div className="h-6 w-24 animate-pulse rounded bg-zinc-100" />
              {[1, 2, 3].map((j) => <div key={j} className="h-40 animate-pulse rounded-xl bg-zinc-100" />)}
            </div>
          ))}
        </div>
      ) : (
        <div className="flex gap-6 flex-1 min-h-0 overflow-x-auto pb-4">
          {columns.map((col) => (
            <div key={col.id} className="flex-1 min-w-[300px] flex flex-col">
              <div className="flex items-center justify-between mb-4">
                <div className="flex items-center gap-2">
                  <div className={`h-2 w-2 rounded-full ${col.color}`} />
                  <h2 className="text-sm font-semibold text-zinc-700">{col.label}</h2>
                  <span className="text-xs text-zinc-400">{col.cards.length}</span>
                </div>
                <button className="text-zinc-300 hover:text-zinc-500 transition-colors">
                  <MoreHorizontal size={14} />
                </button>
              </div>

              <div className="space-y-3 flex-1 overflow-y-auto min-h-[200px]">
                {col.cards.length === 0 ? (
                  <div className="flex items-center justify-center h-32 rounded-xl border border-dashed border-zinc-200 bg-zinc-50/50">
                    <p className="text-xs text-zinc-400">No signals</p>
                  </div>
                ) : (
                  col.cards.map((s, i) => <KanbanCard key={s.id} signal={s} index={i} isManager={isManager} onExport={setExportSignal} />)
                )}
              </div>

              <button
                onClick={() => setCreatingIn(creatingIn === col.id ? null : col.id)}
                className="flex items-center gap-1.5 mt-3 px-3 py-2 rounded-lg text-xs font-medium text-zinc-400 hover:text-zinc-700 hover:bg-zinc-50 border border-transparent hover:border-[#EFEFEF] transition-colors"
              >
                <Plus size={13} />
                Create Signal
              </button>

              {creatingIn === col.id && (
                <CreateSignalForm onClose={() => setCreatingIn(null)} onCreated={refresh} />
              )}
            </div>
          ))}
        </div>
      )}

      {exportSignal && (
        <RoadmapExportModal signal={exportSignal} onClose={() => setExportSignal(null)} />
      )}
    </motion.div>
  );
}
