import { Brain } from "lucide-react";

export default function RootCausePanel({ signal }) {
  return (
    <div className="rounded-2xl border border-zinc-800 bg-zinc-900 p-6">

      <div className="flex items-center gap-3">

        <div className="rounded-xl bg-violet-500/20 p-3">

          <Brain className="text-violet-400" size={22} />

        </div>

        <div>

          <h2 className="text-xl font-semibold">

            AI Root Cause Analysis

          </h2>

          <p className="text-sm text-zinc-500">

            Generated by Root Cause Agent

          </p>

        </div>

      </div>

      <p className="mt-6 leading-8 text-zinc-300">

        {signal.rootCause}

      </p>

    </div>
  );
}